name: Run Cypress tests
on: [push]
jobs:
    install:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Cypress run
          uses: cypress-io/github-action@v6
          with:
            install-command: npm ci --legacy-peer-deps
            project: cypress
            browser: chrome
            build: npm run build
            start: npm run start


# on: push
# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         with: 
#                 working-directory: client
#                 start: npm run start
#                 build: npm run build
#                 project: ./src

